### ISSUE TITLE
Sounds [Linux]

### ISSUE THREAD

**Issue by hssavant** [speedvoltage/hl2mp-essential-fixes#6]
Disclaimer: I'm using docker.

I can get everything to work perfectly, except for some of the sounds (healthkit pickups, charger, etc...)

Steamcmd doesn't seem to be installing the files mentioned in the fix to the server root, so they must be either moved or referenced like so:
ln -s bin/soundemittersystem_srv.so soundemittersystem.so
ln -s bin/scenefilecache_srv.so scenefilecache.so
mv bin/libtier0.so bin/libtier0.so.bak
ln -s bin/libtier0_srv.so bin/libtier0.so
mv bin/libvstdlib.so bin/libvstdlib.so.bak
ln -s bin/libvstdlib_srv.so bin/libvstdlib.so

I'm also seeing lots of
> Warning! Client listens to event 'take_health' unknown by server. 

in the game console, as well as lots of

> CSoundscapeSystem::Init:  Manifest 'scripts/soundscapes_manifest.txt' with bogus file type '', expecting 'file'

and

> Setting invalid soundscape, prison.showers, as the active soundscape. There is probably no script entry matching this name. BUG THIS!

in the docker logs.

I'm unsure which part of the package or libraries are actually addressing the sounds, where to look, or what's related to the issue.

**Comment by speedvoltage** [comment]
```ln -s bin/soundemittersystem_srv.so soundemittersystem.so
ln -s bin/scenefilecache_srv.so scenefilecache.so
mv bin/libtier0.so bin/libtier0.so.bak
ln -s bin/libtier0_srv.so bin/libtier0.so
mv bin/libvstdlib.so bin/libvstdlib.so.bak
ln -s bin/libvstdlib_srv.so bin/libvstdlib.so```
This was mentioned in the README, but not on the release notes, so I have updated that page with this.

`Setting invalid soundscape, prison.showers, as the active soundscape. There is probably no script entry matching this name. BUG THIS!`

Nothing I want to touch with this. This was part of the code hacky implementation update to get those binaries available post anniversary update.

As for the missing sounds, I have reproduced the issue and will push a fix.

Cheers!
